### ISSUE TITLE
Find an alternative to `chronic_duration`, which seems to be dead

### ISSUE THREAD

**Issue by DannyBen** [kenaniah/sidekiq-status#14]
First of all, as I understand there was a maintainer switch (recently?), so congratulations and thanks are in order.

The [chronic_duration](https://github.com/henrypoydar/chronic_duration) dependency seems to be dead (last updated in 2015).

It has a [too specific version dependency on an older `numerizer` gem](https://github.com/henrypoydar/chronic_duration/blob/01ea7446843879c219c9e49b912f1db6f8f17198/chronic_duration.gemspec#L22), so anyone using this gem will always have an outdated gem version.

Can this dependency be replaced maybe?

**Comment by kenaniah** [comment]
@DannyBen please feel free to open a PR that replaces the dependency if you'd like. But unless there's a security concern or a bug, there does not seem to be any inherent benefit in doing so from my perspective. Closing for now.
