### ISSUE TITLE
Breaking sidekiq v6.5.4

### ISSUE THREAD

**Issue by jensenbox** [kenaniah/sidekiq-status#16]
The latest version of sidekiq is breaking the gem - https://github.com/mperham/sidekiq/issues/5462#issuecomment-1209985257

I am not sure what the fix is for this Gem.

Additional details on what is breaking can be found in the link above.

**Comment by denisj** [comment]
MAybe add in the file lib/sidekiq-status/server_middleware.rb, the line `require 'sidekiq/component'` above `require 'sidekiq/job_retry'`?

**Comment by joelmoss** [comment]
See https://github.com/mperham/sidekiq/issues/5462#issuecomment-1209985257

**Comment by denisj** [comment]
It seems that sidekiq have fixed it too https://github.com/mperham/sidekiq/commit/9d5a6d7fa7edba006db86fc520fbcd353005cf9c

**Comment by kenaniah** [comment]
I'm going to close this issue out as it has been addressed upstream.
