### ISSUE TITLE
Perfomance of the sidekiq status ui page

### ISSUE THREAD

**Issue by sliusar-ihor** [kenaniah/sidekiq-status#18]
Sidekiq status page works extremely slow when It has a big amount of statuses(over 100000).
The main issue in this line https://github.com/kenaniah/sidekiq-status/blob/main/lib/sidekiq-status/web.rb#L92

The page loads all matching keys into memory in order to do pagination and sorting in memory. As well as the Sidekiq::Status.get_all jid calls for every sidekiq::status jid, prior to pagination

Did anyone try to fix this problem?

**Comment by kenaniah** [comment]
@sliusar-ihor not to my knowledge, but feel free to open a PR if you have a path to solving / improving the behavior of this use case. That said, I'm closing this for now until such time that a PR is submitted.
