### ISSUE TITLE
UI queue delete does not delete sidekiq:status:{job_id} from Redis

### ISSUE THREAD

**Issue by galatt** [kenaniah/sidekiq-status#19]
Hello,

We found a strange behavior using sidekiq ui when deleting the queue. Once we delete the queue the sidekiq:status:#{job_id} key still exists with queued value, so when we check the status via status(job_id) (sidekiq-status 2.1.0) in our application it says the job is still in queued state (however it doesn't exist anymore in the queue).

**Comment by kenaniah** [comment]
@galatt please feel free to re-open and post reproduction steps to show the suspected buggy behavior. Closing for now as non-actionable.
