### ISSUE TITLE
rails-sidekiq-status-is-empty-in-redis

### ISSUE THREAD

**Issue by ciscolive** [kenaniah/sidekiq-status#2]
I'm using sidekiq for background processing and sidekiq-status for job progress tracking.

Using:

Ruby 2.5.1
Rails 5.1.6
Redis 4.0.1
Sidekiq 5.1.3
Sidekiq-status 1.0.2
Redis is up and running. Background process is working normal. I put binding.pry in process and start testing:

```ruby
job_id = MyJob.perform_async(*args)

Sidekiq::Status::queued?      job_id => false
Sidekiq::Status::working?     job_id => false
Sidekiq::Status::complete?    job_id => false
Sidekiq::Status::failed?      job_id => false

status = Sidekiq::Status::status(job_id) #=> {} (empty)
```

When I open web monitor http://localhost:3000/sidekiq/statuses for sidekiq, stasuses are empty.

job_id that I get from app console is different than "almighty:16288:dea0b989e20f".

After running redis-cli and keys * I get:

```
127.0.0.1:6379> keys *
1) "almighty:16288:dea0b989e20f:workers"
2) "stat:failed:2018-08-10"
3) "queues"
4) "stat:failed"
5) "stat:processed:2018-08-10"
6) "almighty:16288:dea0b989e20f"
7) "processes"
8) "stat:processed"
9) "sidekiq:status:"
```
And then hgetall "sidekiq:status:"

```
127.0.0.1:6379> hgetall "sidekiq:status:"
 1) "update_time"
 2) "1533929922"
 3) "at"
 4) "23.529411764705884"
 5) "total"
 6) "100"
 7) "pct_complete"
 8) "23"
 9) "message"
10) "Clustering data..."
```
So, some data about process is here, but not by job_id. And when the job is done, "sidekiq:status:" is gone. I assume, something is wrong with storing data in redis from sidekiq?

```ruby
# config/initializers/sidekiq.rb:

require 'sidekiq'
require 'sidekiq-status'

Sidekiq.configure_client do |config|
  config.redis = { :size => 1 } #, url: ENV['REDIS_URL']
  # accepts :expiration (optional)
  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes

  config.redis = { url: 'redis://localhost:6379/0' }
end

Sidekiq.configure_server do |config|
  # accepts :expiration (optional)
  Sidekiq::Status.configure_server_middleware config, expiration: 30.minutes

  # accepts :expiration (optional)
  Sidekiq::Status.configure_client_middleware config, expiration: 30.minutes

  config.redis = { url: 'redis://localhost:6379/0' }
end
```
```ruby
# config/initializers/redis.rb:

Redis.current = Redis.new(:host => '127.0.0.1', :port => 6379)
```
```ruby
# config/application.rb:

config.cache_store = :redis_store, "redis://localhost:6379/0/cache", { expires_in: 90.minutes }
```
ruby-on-rails

**Comment by kenaniah** [comment]
@ciscolive thanks for the report. Do you still experience the same issue if you update to sidekiq 6.x and sidekiq-status 2.1.0?

The `config.redis = ...` lines look suspicious -- especially in the `Sidekiq.configure_client` block. It looks like the URL might be getting unset as you replace the entire hash with just `{ :size => 1 }`. 

Please feel free to re-open if you're still having issues.
