### ISSUE TITLE
Issues with Heroku and Sidekiq-Status

### ISSUE THREAD

**Issue by Trimakas** [kenaniah/sidekiq-status#24]
I'm on 

- ruby 2.7.0
- Rails 6.1.7.2 
- Sidekiq 6.5.4
- Sidekiq-Status 2.1.3
- Heroku-18 stack

When I push WITHOUT Sidekiq Status all is well. (Literally just comment out the gem in my gemfile, and re-run `bundle`)

When I re-enable the gem and `bundle` Heroku fails with the following errors:

` !     rake aborted!
 !     NameError: uninitialized constant Sidekiq::Component
 !     Did you mean?  Complex
 !     /tmp/build_820f59ae/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:66:in `<class:JobRetry>'
 !     /tmp/build_820f59ae/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:61:in `<module:Sidekiq>'
 !     /tmp/build_820f59ae/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.5.4/lib/sidekiq/job_retry.rb:6:in `<top (required)>'
 !     /tmp/build_820f59ae/vendor/bundle/ruby/2.7.0/gems/sidekiq-status-2.1.3/lib/sidekiq-status/server_middleware.rb:2:in `<top (required)>'
 !     /tmp/build_820f59ae/vendor/bundle/ruby/2.7.0/gems/sidekiq-status-2.1.3/lib/sidekiq-status.rb:6:in `<top (required)>'`

Anyone seen this before? Oh and locally everything is fine.

WOW, UPDATE:
Wow, I can't believe it, but it was my sidekiq version. I was on, as you can see, 6.5.4 and it was failing but only on Heroku.

This might be a great idea to put this in the docs or something. To keep folks from spending days on this issue.

**Comment by kenaniah** [comment]
Sounds like the issue was actually upstream in Sidekiq (which isn't unusual to see, sadly). Closing this out.
