### ISSUE TITLE
Unsupported command argument type: ActiveSupport::Duration

### ISSUE THREAD

**Issue by acflint** [kenaniah/sidekiq-status#27]
Hi all. 

When I have sidekiq-status included in the Sidekiq initializer, I get the error mentioned in the title.

This is my config:

```ruby
require "sidekiq-status"

Sidekiq.configure_server do |config|
  if Rails.env.production?
    config.redis = {url: ENV["REDIS_URL"], ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE}}
  end

  Sidekiq::Status.configure_server_middleware config, expiration: 2.days
  Sidekiq::Status.configure_client_middleware config, expiration: 2.days
end

Sidekiq.configure_client do |config|
  if Rails.env.production?
    config.redis = {url: ENV["REDIS_URL"], ssl_params: {verify_mode: OpenSSL::SSL::VERIFY_NONE}}
  end

  Sidekiq::Status.configure_client_middleware config, expiration: 2.days
end
```

I also tried `2880.minutes` to more closely match the documented configuration, but it caused the same error.

I'm running:
Sidekiq 7.0.3
Redis 7.0.5
sidekiq-status 3.0.0
Rails 7.0.4
Ruby 3.2.0

Thanks!

**Comment by Skulli** [comment]
Having the same error once i start any job with `perform_later`. If i comment out `expiration: ...`, it works.

**Comment by kenaniah** [comment]
@Skulli would you be able to post the backtrace for your exception? I suspect the issue may have to do with the upstream Redis client that Sidekiq 7 uses. If what I'm suspecting is the issue, then it might be best to update `sidekiq-status`'s docs to not use activesupport's durations.

**Comment by Skulli** [comment]
Called within rails console

    Failed enqueuing XXX to Sidekiq(default): TypeError (Unsupported command argument type: ActiveSupport::Duration)
    TypeError: Unsupported command argument type: ActiveSupport::Duration
    from /Users/xxx/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/redis-client0.12.1/lib/redis_client/command_builder.rb:37:in `block in generate'

**Comment by Skulli** [comment]
See https://github.com/redis-rb/redis-client/blob/master/lib/redis_client/command_builder.rb#L37

working  with `24.hours.to_i`

**Comment by kenaniah** [comment]
This is due to Sidekiq 7 switching out the underlying Redis library, and isn't actually a bug in `sidekiq-status`. That said, I have updated the readme's documentation to pass `Integer` values instead of `ActiveSupport::Duration` values, as this should be compatible with the both Redis libraries.
