### ISSUE TITLE
Clicking on remove button throws a 404

### ISSUE THREAD

**Issue by GMolini** [kenaniah/sidekiq-status#28]
Gem version: 3.0.0
rails version: 7.0.2.2

![image](https://user-images.githubusercontent.com/1327783/218746060-d8191efe-5c13-46af-92ea-5d9500ba98a2.png)

When I click on the remove button in the web ui I get an `No route matches [POST] "/statuses"`. There seems to be an issue similar to this in the original repo: https://github.com/utgarda/sidekiq-status/issues/145, but it was marked as closed and It still happens for me

**Comment by kenaniah** [comment]
@GMolini could you please confirm that you are indeed using `Rack::MethodOverride` in your rack middleware? Would you also be able to advise if this is a regression specific to v.3.0.0 (as in, does it work as expected if you downgrade `sidekiq-status` to 2.x)?

**Comment by GMolini** [comment]
Mm I thought it was closed because they had implemented the fix. How do you add the `Rack::MethodOverride`?

**Comment by kenaniah** [comment]
@GMolini please RTM. In particular, this Rails guide on using Rack: https://guides.rubyonrails.org/rails_on_rack.html
