### ISSUE TITLE
Client middleware does not create status record if you enqueue the job from another app

### ISSUE THREAD

**Issue by hwo411** [kenaniah/sidekiq-status#29]
Hi everyone.

I noticed this in our environment when pushed a job from one app that's handled by another app. The sidekiq-status middleware was enabled in both apps.

What I see in sidekiq ui is basically this: 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/4161883/225230785-1208ca50-7dd3-4275-bc0e-faebb69543af.png">

As I understand from this code https://github.com/kenaniah/sidekiq-status/blob/main/lib/sidekiq-status/client_middleware.rb#L22-L43
the middleware searches for a class and doesn't find it, therefore does not store the status.

Is this behavior mandatory? Or can it be changed to support pushes from other apps with sidekiq status?

I understand that with this code you can reliably determine whether it's sidekiq job or not. Are there any cases where it doesn't work well if you still store the info if the class does not exist?

**Comment by kenaniah** [comment]
At face value, this use case sounds like a potential anti-pattern. Ideally, the job class should be available to both the client (invoker) and server (executor) middleware. But as I might just simply be unfamiliar, would you be able to outline a scenario in which the job class being accessible to both middlewares is _not_ preferrable?

**Comment by kenaniah** [comment]
@hwo411 closing for now, but feel free to re-open if you have an answer to the question posted above.

**Comment by hwo411** [comment]
Oh, sorry @kenaniah , I missed your reply.

So what's our case. We push some jobs from one our app to be executed by other apps (e.g., with one that sends emails). Ideally, I'd set up RabiitMQ or another pub-sub and send the events there so that email app can just respond to them and so that one app isn't aware of the structure of another app, but at this moment we don't want to add it to our stack (but will do it later). So we went with a simple solution where we push a sidekiq job that is then executed by another app. Our decision was based on that maintaining a separate codebase is more important for us than temporary exposure of a kind of private interface.

Also, I wouldn't consider this an avoid-at-all-cost anti-pattern, because a similar example is even mentioned in sidekiq wiki/FAQ: https://github.com/sidekiq/sidekiq/wiki/FAQ#how-do-i-push-a-job-to-sidekiq-without-ruby
It shows how to do it without sidekiq at all, we still do it with Sidekiq client, just without the job on the sender side.

At the same time, I see that allowing the job that's not available on the client to have status will have the limitations with your middleware, since some parameters of the job are not available. Though I think it'd still be useful to allow the limited status instead of no status.

WDYT?

**Comment by tomasmiguez** [comment]
+1
We are having the same problem. With a similar use case.

**Comment by tomasmiguez** [comment]
@hwo411 in the meanwhile we are doing something kind of ugly but that works fine. It might be helpful for you too, but we didn't test it extensively so it may not work in some cases.

```ruby
  class JobEnqueuer
    include Singleton

    def enqueue(job:, args:)
      JobStub.name = job
      Sidekiq::Client.push('class' => JobStub,
                           'args' => args)
    end

    ##
    # Currently Sidekiq::Status those not support enqueuing with an string as
    # the class. We can't use the real class as it's not declared on this
    # project. Sidekiq::Status only need the class passed as parameter to have
    # Sidekiq::Status::Worker as a member of its ancestors
    # (https://github.com/kenaniah/sidekiq-status/blob/main/lib/sidekiq-status/client_middleware.rb#L22-L43).
    #
    # We also need to take into account what vanilla Sidekiq expects of the
    # class passed as parameter, and it actually just calls to_s on it to get an
    # string representation of the class name, so we stub that method and make
    # it return a class instance variable that can be set to whatever we want.
    #
    # This is a known issue and we should remove this if an alternative is
    # implemented:
    #
    # https://github.com/kenaniah/sidekiq-status/issues/29
    class JobStub
      include Sidekiq::Worker
      include Sidekiq::Status::Worker

      @name = 'JobStub'

      def self.name=(name)
        raise 'Invalid name' unless name.is_a?(String)

        @name = name
      end

      def self.to_s
        @name
      end
    end
  end
```

**Comment by kenaniah** [comment]
I'd be happy to consider a pull request to handle this sort of use case, as long as there is still a clean way to denote which jobs should have status info tracked.

**Comment by tomasmiguez** [comment]
I don't know how that could be achieved without modifying the gem API :/

**Comment by kenaniah** [comment]
I'll convert this to a discussion then, as someone may be able to present a workable solution down the road.
