### ISSUE TITLE
Sidekiq enterprise encryption failed to decrypt with this plugin

### ISSUE THREAD

**Issue by kimyu92** [kenaniah/sidekiq-status#3]
I run into an issue the secret bag is not decrypting properly and fallback to `[encrypted data]` using `sidekiq-status` middleware

Related issues:
https://github.com/mperham/sidekiq/issues/3706
https://github.com/utgarda/sidekiq-status/issues/153

Configuration for sidekiq initializer
```ruby
Sidekiq.configure_client do |config|
  Sidekiq::Status.configure_client_middleware config
end

Sidekiq.configure_server do |config|
  Sidekiq::Status.configure_server_middleware config
  Sidekiq::Status.configure_client_middleware config
end
```

Would there be an elegant workaround for this besides just not using this plugin?

**Comment by kenaniah** [comment]
@kimyu92 just wanted to reach out and see if this was still an issue for you when using sidekiq 6.2.2 and sidekiq-status 2.1.0, or if you were able to find a solution. I don't have access to Sidekiq Enterprise, so unfortunately I can't weigh in on the encryption feature or how the middlewares interact.

**Comment by kenaniah** [comment]
@kimyu92 would you be able to paste your full sidekiq configuration, including the encryption stuff (minus any sensitive keys)? 

My first theory is that it has to do with how the middlewares are ordered. It doesn't sound like this is a bug with either lib just yet.

**Comment by kimyu92** [comment]
Here is the snippet

https://github.com/mperham/sidekiq/issues/3706#issuecomment-878530814

**Comment by kenaniah** [comment]
@kimyu92 as a user of Sidekiq Enterprise, you may be in the best place to debug this. Please feel free to open a PR if there's anything that needs to be updated in sidekiq-status itself.

**Comment by kenaniah** [comment]
Closing as it has been over a year since the last update.
