### ISSUE TITLE
Transition from `Worker` to `Job`

### ISSUE THREAD

**Issue by abrahamparayil** [kenaniah/sidekiq-status#30]
- Sidekiq is standardizing `job` across the ecosystem and gems.
- Reference issue in Sidekiq: https://github.com/sidekiq/sidekiq/issues/4955.

**Comment by kenaniah** [comment]
Thanks for the PR, but I do not feel that renaming part of the API to match the whims of the maintainer of a related gem is necessary nor justified. There does not appear to be any intrinsic benefit to this change, especially given that it will eventually mean more work for the end users of the sidekiq-status gem.
