### ISSUE TITLE
Sidekiq v6.2.2 renamed `Job` to `JobRecord`

### ISSUE THREAD

**Issue by doits** [kenaniah/sidekiq-status#4]
See https://github.com/mperham/sidekiq/commit/f1b24da9c225a5512120514d32a5348760e92f3a

More interestingly, a *new* `Sidekiq::Job` got added – https://github.com/mperham/sidekiq/commit/8e36432662421e79cf14096e9467666b6827f82d –  which is the old `Sidekiq::Worker`, it seems.

Looks like they wanted to break everyone using the old `Sidekiq::Job` now so it gets noticed. Really bold step IMO (could have been deprecated at least for a minor version), but it is what it is.

See https://github.com/mperham/sidekiq/discussions/4971 for the full discussion.

Just a heads up from me for now.

**Comment by doits** [comment]
Got a PR ready in #5 which should fix it.

**Comment by debow77** [comment]
Is there an ETA on [5](https://github.com/kenaniah/sidekiq-status/pull/5) being released?

**Comment by kenaniah** [comment]
This has been fixed in v2.1.0 via PR https://github.com/kenaniah/sidekiq-status/pull/9
